#!/usr/bin/env python3
'''
script de borrar mapa
'''
import os
import sys

try:
    PROXY = sys.argv[1]
    TOKEN = sys.argv[2]
    NOMBRE = sys.argv[3]
except ValueError:
    print('Command arguments: {} <PROXY> <TOKEN> <NOMBRE DEL MAPA>'.format(
        os.path.basename(sys.argv[0]))
        )
    sys.exit(1)
os.system("python3 ./map_manager_client.py "+"'"+PROXY+"' "+TOKEN+" -d "+NOMBRE)
