#!/usr/bin/env python3
'''
script de run game
'''
import json
import os
PROXY_JUEGO = "proxy_juego.json"
proxy = {}
if os.path.exists(PROXY_JUEGO):
    with open(PROXY_JUEGO, 'r') as contents:
        proxy = json.load(contents)
print(proxy.get("proxy", None))
